name: eztrainz
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  youtube_player_flutter: ^9.1.2
  flutter_launcher_icons: ^0.14.4
  number_pagination: ^1.1.6
  wrapbuilder: ^0.0.1
  fl_chart: ^1.1.1
  audioplayers: ^6.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/audio/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/Poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/Poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/Poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/Poppins/Poppins-Black.ttf
          weight: 900
        - asset: assets/Poppins/Poppins-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/Poppins/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/Poppins/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/Poppins/Poppins-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/Poppins/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/Poppins/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/Poppins/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/Poppins/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/Poppins/Poppins-BlackItalic.ttf
          weight: 900
          style: italic

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo2.png"
