name: eztrainz
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  youtube_player_flutter: ^9.1.2
  flutter_launcher_icons: ^0.14.4
  number_pagination: ^1.1.6
  wrapbuilder: ^0.0.1
  fl_chart: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/


flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo2.png" # path to your logo image
